[project]
name = "vrage"
dynamic = ["version"]
description = "A Python client for the VRage Remote API of Space Engineers 1"
license = "MIT"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment :: Simulation",
    "Typing :: Typed",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "vrage/_version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"

[project.urls]
Repository = "https://github.com/space-engineers-tools/python-vrage"
